### ISSUE TITLE
Exception handling in operations accessing DB

### ISSUE THREAD

**Issue by cristicatalan** [icelab/berg#130]
I investigated a little the approach of writing operations on Berg and I have concerns regarding edge cases where it is possible to have exceptions raised as in [here](https://github.com/icelab/berg/blob/master/apps/admin/lib/admin/posts/operations/create.rb).

Isn't operations like create a good use case for the Try monad with a base exception for DB? The Try monad docs states `The Try monad is useful when you want to wrap some code that can raise exceptions of certain types. A common example is making an HTTP request or querying a database.`

How do you handle in Berg exceptions in situations such as create operation?

**Comment by timriley** [comment]
In this case, if we receive an exception from writing to the database, it represents some kind of programmer error, and we _want_ it to be noisy (i.e. go unhandled, crash the page, notify our exception tracker) so we can see the problem and fix the bug.

**Comment by cristicatalan** [comment]
Cool thanks.
