### ISSUE TITLE
Header/line colour combos

### ISSUE THREAD

**Issue by makenosound** [icelab/berg#64]
I think we want to keep the line/header colours the same base colour (potentially with different tints) wherever possible. The exception being where we use _grey_ headers we could have whatever colour lines since they don’t clash.

**Comment by andyicelab** [comment]
Cool — I can adjust. I think there was an instance in the designs where the blue text and line colour differed which I've replicated, but I agree they should be the same.

**Comment by andyicelab** [comment]
Adjusted in: https://github.com/icelab/berg-assets/commit/98118456dd5bce6e1ec22092b472c73b255979f2
