### ISSUE TITLE
Remove font-awesome

### ISSUE THREAD

**Issue by makenosound** [icelab/berg#66]
We don’t really use many glyphs — could be get away with just SVGs for the few we do?

**Comment by andyicelab** [comment]
Yeah, I reckon that'd be good. Wonder if https://fortawesome.com would be worth a try. Only issue I can see is that the free option makes you CDN-serve. Otherwise we could just SVG the glyphs we use.

**Comment by makenosound** [comment]
Hrm, I’d rather not have another external dependency. Ideally we could simply use inline SVGs in the few places we have these glyphs.

**Comment by andyicelab** [comment]
Have ripped out Font Awesome and replaced with a custom subset with only the glyphs we're using + bare bones CSS: https://github.com/icelab/berg-assets/commit/47b12bac1c384666d80659a407cfa60ce9f95b58

**Comment by makenosound** [comment]
This seems reasonable to me, though I reckon we could still just use inline SVGs wherever you want to use these. Any reason for not doing that?

**Comment by andyicelab** [comment]
There's a bunch of places where I'm altering the size for different breakpoints and a couple of spots I'm altering the colours etc. Seems like a lot of work to me to inline these and have to replicate those style changes. Is there a bigger win we'd get with that approach?

**Comment by makenosound** [comment]
I think that’d be pretty easy to do if you have a little wrapping div with those class changes — inline SVGs allow you to alter the appearance entirely in CSS.

> Is there a bigger win we'd get with that approach?

The main win is just avoiding loading external resources all the time (even if they’re small).

**Comment by andyicelab** [comment]
Wouldn't we then be loading 6 or 7 SVGs versus a couple of font files? Sorry — just want to get my head around the approach first :)

**Comment by makenosound** [comment]
Ah, that’s why I keep saying _inline_ SVGs, not just SVGs. I mean literally writing the SVG into the template:

```
span.svg-wrapper.color-blue.bordercolor-red
  erb:
    <svg> ...
```

**Comment by andyicelab** [comment]
Oh, right! Sorry — I was reading that as an _element_ in the template with SVG backgrounds. Yes, this is much nicer. Shall do.

**Comment by makenosound** [comment]
@andyicelab Not quite sure how to do it in dry-web land, but we could also make some little helpers to make it easy to reuse these sort of things throughout.

**Comment by andyicelab** [comment]
Hey @makenosound — have ripped out the icon font and used the inline SVG technique instead.

**Comment by makenosound** [comment]
@andyicelab Cool, happy to close this!
