### ISSUE TITLE
Adjust Markdown settings

### ISSUE THREAD

**Issue by makenosound** [icelab/berg#74]
Looks like Redcarpet is interpreting `_foo_` as `<u>foo</u>` whereas we’d expect it to be `<em>foo</em>`.

**Comment by dNitza** [comment]
Offending codes:

- https://github.com/icelab/berg/blob/6c948561f8c6cd90a469a5fd4273a67c3b5ef01e/apps/main/lib/main/decorators/public_project.rb
- https://github.com/icelab/berg/blob/1f54e99f59e7b081369a583c8ab2fbc33eedabfc/apps/main/lib/main/decorators/public_person.rb
- https://github.com/icelab/berg/blob/2079d74e35a09aff2b728fde512c3eec41d266a1/apps/main/lib/main/decorators/public_post.rb

**Comment by dylanwolff** [comment]
This has been fixed in this commit: https://github.com/icelab/berg/commit/1664475aa27d9710f42c773e71883538ff6fff7e
