### ISSUE TITLE
Add SmartyPants to Markdown rendering

### ISSUE THREAD

**Issue by makenosound** [icelab/berg#82]

**Comment by dylanwolff** [comment]
I've implemented this and it's correctly rendering smart entities for content rendered by `StandardRenderer` but not single line content rendered by `HTMLWithoutBlockElements`. Needs further investigation.

**Comment by makenosound** [comment]
This is an educated guess, but I reckon it’s because we’re overriding `postprocess` in that class, and that’s likely where the `SmartyPants` stuff would get called.
